# Mini-projet : SPARQL et préparation de données pour la recherche
Ce notebook a pour but de montrer comment transformer des données issues d’un graphe de connaissances en un jeu de données clair et réutilisable pour la recherche.

À partir d’informations extraites depuis une source ouverte, le travail consiste à vérifier, nettoyer et organiser les données afin qu’elles puissent être facilement comprises, partagées et exploitées par des chercheurs, ou intégrées plus tard dans une base de connaissances.

## Aperçu du pipeline
<p style="text-align: center;">
  <img src="images/pipeline_overview.png" width="70%">
</p>

## Source des données
<p style="text-align: center;">
  <img src="images/Wikidata-logo.png" width="10%">
</p>

Les données proviennent de Wikidata, un référentiel ouvert et multilingue du web sémantique. Il sert fréquemment de point d’appui pour l’enrichissement, l’alignement et la standardisation des données en humanités numériques.

In [1]:
import requests
import pandas as pd
from pathlib import Path

In [14]:
response.raise_for_status()

In [18]:
# Query path
query_path = Path("queries/authors.rq")
query = query_path.read_text()

# Endpoint wikidata
url = "https://query.wikidata.org/sparql"

# Send request
response = requests.get(
    url,
    params={"format": "json", "query": query},
    headers={"User-Agent": "sparql-demo"}
)

response.raise_for_status()

data = response.json()["results"]["bindings"]
data

[{'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q272'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q270230'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1888-03-13T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Paul Morand'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': '8e arrondissement de Paris'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q493'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q2960786'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1854-10-20T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Arthur Rimbaud'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Charleville'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q501'},
  'birthPlace': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q90'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1821-04-09T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Charles Baudelaire'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Paris'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q501'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q15149908'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1821-04-09T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Charles Baudelaire'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'ancien 11e arrondissement de Paris'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q502'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q1289'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1783-01-23T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Stendhal'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Grenoble'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q504'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q3449906'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1840-04-02T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Émile Zola'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'rue Saint-Joseph'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q535'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q37776'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1802-02-26T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Victor Hugo'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Besançon'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q539'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q33959'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1807-07-04T00:00:00Z'},
  'authorLabel': {'type': 'literal', 'value': 'Q539'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Nice'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q563'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q202368'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1939-06-24T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Brigitte Fontaine'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Morlaix'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q755'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q22690'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1844-03-30T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Paul Verlaine'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Metz'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q767'},
  'birthPlace': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q90'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1842-03-18T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Stéphane Mallarmé'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Paris'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q1151'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q864123'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1803-12-11T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Hector Berlioz'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'La Côte-Saint-André'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q1488'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q6730'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1909-03-31T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Robert Brasillach'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Perpignan'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q1698'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q230127'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1928-04-02T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Serge Gainsbourg'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': '4e arrondissement de Paris'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q1716'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q191066'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1952-05-11T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Renaud'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': '15e arrondissement de Paris'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q2908'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q456'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1900-06-29T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Antoine de Saint-Exupéry'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Lyon'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q2908'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q3344'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1900-06-29T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Antoine de Saint-Exupéry'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': '2e arrondissement de Lyon'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q3048'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q237516'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1868-04-20T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Charles Maurras'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Martigues'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q3335'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q1774606'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1903-06-25T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'George Orwell'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Motihari'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q3816'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q2845758'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1804-07-01T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'George Sand'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'ancien 6e arrondissement de Paris'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q4128'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q194420'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1897-10-03T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Louis Aragon'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': '16e arrondissement de Paris'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q4137'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q649'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1896-09-24T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Elsa Triolet'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Moscou'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q18420'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q586464'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1522-01-01T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Joachim du Bellay'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Liré'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q18832'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q2145650'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1930-06-26T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Sławomir Mrożek'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Borzęcin'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q18832'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q2145650'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1930-06-29T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Sławomir Mrożek'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Borzęcin'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q19054'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q17338'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1485-01-01T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Mathieu Bandello'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Castelnuovo Scrivia'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q20730'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q6548'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1919-12-30T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Pierre Delaire'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Orléans'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q20731'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q647'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1921-02-03T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Per Denez'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Rennes'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q20733'},
  'birthPlace': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q90'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1884-06-30T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Georges Duhamel'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Paris'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q20951'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q320233'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1830-03-15T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Élisée Reclus'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Sainte-Foy-la-Grande'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q22750'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q217180'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1890-11-29T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Maurice Genevoix'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Decize'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q23441'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q844701'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1848-02-16T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Octave Mirbeau'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Trévières'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q23844'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q49241'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1961-05-06T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'George Clooney'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Lexington'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q24979'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q865745'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1795-06-19T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Maxime Raybaud'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'La Colle-sur-Loup'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q27645'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q2111332'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1814-05-30T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Mikhaïl Bakounine'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Priamoukhino'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q27764'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q217180'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1767-08-25T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Louis Antoine de Saint-Just'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Decize'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q12054'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q7880'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1961-09-18T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Bernard Werber'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Toulouse'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q12091'},
  'birthPlace': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q71'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1828-05-08T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Henry Dunant'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Genève'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q12571'},
  'birthPlace': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q71'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1889-08-19T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Edmond Privat'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Genève'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q12622'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q648'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1901-07-29T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Gaston Waringhien'},
  'birthPlaceLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Lille'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q12688'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q188776'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1859-09-03T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr', 'type': 'literal', 'value': 'Jean Jaurès'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Castres'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q12718'},
  'birthPlace': {'type': 'uri',
   'value': 'http://www.wikidata.org/entity/Q6441'},
  'birthDate': {'datatype': 'http://www.w3.org/2001/XMLSchema#dateTime',
   'type': 'literal',
   'value': '1798-01-19T00:00:00Z'},
  'authorLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Auguste Comte'},
  'birthPlaceLabel': {'xml:lang': 'fr',
   'type': 'literal',
   'value': 'Montpellier'}},
 {'author': {'type': 'uri', 'value': 'http://www.wikidata.org/entity/Q12942'},
  'birthPlace': {'type': 'uri',

In [3]:
# Transform into dataframe
rows = []
for item in data:
    rows.append({
        "author": item.get("authorLabel", {}).get("value"),
        "birthDate": item.get("birthDate", {}).get("value"),
        "birthPlace": item.get("birthPlaceLabel", {}).get("value"),
    })

df = pd.DataFrame(rows)
print("DataFrame shape :")
print(df.shape)
df.head()

DataFrame shape :
(100, 3)

,author,birthDate,birthPlace
0,Paul Morand,1888-03-13T00:00:00Z,8e arrondissement de Paris
1,Arthur Rimbaud,1854-10-20T00:00:00Z,Charleville
2,Charles Baudelaire,1821-04-09T00:00:00Z,Paris
3,Charles Baudelaire,1821-04-09T00:00:00Z,ancien 11e arrondissement de Paris
4,Stendhal,1783-01-23T00:00:00Z,Grenoble

In [4]:
# Save file
output_path = Path("data/authors.csv")
output_path.parent.mkdir(exist_ok=True)
df.to_csv(output_path, index=False)

## 2. Data curation step
Opérations principales :

- Analyser et simplifier les informations temporelles
- Nettoyer les champs textuels
- Supprimer les enregistrements incomplets
- Créer des identifiants internes stables

In [5]:
# Normalize dates (keep only the year)
df["birthYear"] = pd.to_datetime(
    df["birthDate"], errors="coerce"
).dt.year
df["birthYear"] = df["birthYear"].astype("Int64")

df.head()

,author,birthDate,birthPlace,birthYear
0,Paul Morand,1888-03-13T00:00:00Z,8e arrondissement de Paris,1888
1,Arthur Rimbaud,1854-10-20T00:00:00Z,Charleville,1854
2,Charles Baudelaire,1821-04-09T00:00:00Z,Paris,1821
3,Charles Baudelaire,1821-04-09T00:00:00Z,ancien 11e arrondissement de Paris,1821
4,Stendhal,1783-01-23T00:00:00Z,Grenoble,1783

In [6]:
# Clean text (remove extra spaces and ensure consistent string formatting)
df["author"] = df["author"].astype(str).str.strip()
df["birthPlace"] = df["birthPlace"].astype(str).str.strip()
print("Rows after cleaning:", len(df))

,author,birthDate,birthPlace,birthYear
0,Paul Morand,1888-03-13T00:00:00Z,8e arrondissement de Paris,1888
1,Arthur Rimbaud,1854-10-20T00:00:00Z,Charleville,1854
2,Charles Baudelaire,1821-04-09T00:00:00Z,Paris,1821
3,Charles Baudelaire,1821-04-09T00:00:00Z,ancien 11e arrondissement de Paris,1821
4,Stendhal,1783-01-23T00:00:00Z,Grenoble,1783

In [7]:
# Remove incomplete records
before = len(df)
df = df.dropna(subset=["author", "birthYear"])
after = len(df)
print("Rows after cleaning:", len(df))

Removed 1 incomplete rows

In [8]:
# Create internal identifiers
df["internal_id"] = range(1, len(df) + 1)

# Select final columns
df = df[["internal_id", "author", "birthYear", "birthPlace"]]
df.head()

,internal_id,author,birthYear,birthPlace
0,1,Paul Morand,1888,8e arrondissement de Paris
1,2,Arthur Rimbaud,1854,Charleville
2,3,Charles Baudelaire,1821,Paris
3,4,Charles Baudelaire,1821,ancien 11e arrondissement de Paris
4,5,Stendhal,1783,Grenoble

In [9]:
# Deduplicate authors
df = df.sort_values("internal_id")
df = df.drop_duplicates(subset=["author", "birthYear"], keep="first")
print("Rows after cleaning:", len(df))

After dedup: 93

In [13]:
# 3. Reset identifiers
df = df.reset_index(drop=True)
df["internal_id"] = range(1, len(df) + 1)
print("DataFrame shape :")
print(df.shape)
df.head()

DataFrame shape :
(93, 4)

,internal_id,author,birthYear,birthPlace
0,1,Paul Morand,1888,8e arrondissement de Paris
1,2,Arthur Rimbaud,1854,Charleville
2,3,Charles Baudelaire,1821,Paris
3,4,Stendhal,1783,Grenoble
4,5,Émile Zola,1840,rue Saint-Joseph
...,...,...,...,...
88,89,Hubert Rouger,1875,Calvisson
89,90,Oscar Wilde,1854,Dublin
90,91,Maurice Alhoy,1802,Paris
91,92,Henry Murger,1822,ancien 2e arrondissement de Paris
92,93,Daniel Yvinec,1963,Vannes

In [11]:
# Save file
output_path = Path("data/authors_curated.csv")
output_path.parent.mkdir(exist_ok=True)
df.to_csv(output_path, index=False)